services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    command: python main.py

  database:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fx_wallet
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
