services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    command: python main.py

  database:
    image: postgres:16
    env_file:
      - secrets.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
